version: '3.8'

services:
  web:
    build: .
    container_name: django_library_app
    env_file: .env
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  certbot-etc:
  certbot-www: